---
- name: install apache
  become: true
  ansible.builtin.yum:
    name: httpd
    state: present

- name: install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present

- name: clone tooling repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/mmuhammad0/tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content up one level
  become: true
  command: cp -r /var/www/html/html/ /var/www/

- name: ensure httpd is started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: remove nested html folder
  become: true
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent
